import { describe, expect, it } from "vitest";
import { parseDBML } from "../parser/dbml";

// 针对第二次审计的回归测试：
//   2. 顶层散行（Note: '...' 等）不再把下一个 Table 块吞成 body
//   4. rel.from 指向缺失表时解析器仍产出关系并告警（builder 端补占位实体）
//   5. `<` / `<>` 的 FK 归属侧与菱形标签
//   6. 表别名（Table x as Y）在 Ref 中生效
//   12. Unicode（日文假名 / 韩文谚文）标识符
//   13. 同名表重复定义警告

describe("parseDBML — 顶层散行不吞表", () => {
  it("Note: '...' 散行后面的两张表都能解析，且发一条警告", () => {
    const r = parseDBML(
      "Note: 'generated by tool'\nTable users { id int [pk] }\nTable orders { id int [pk] }",
    );
    expect(r.tables.map((t) => t.name)).toEqual(["users", "orders"]);
    expect(r.warnings).toEqual([
      {
        code: "statement_skipped",
        message:
          "line 1: top-level line \"Note: 'generated by tool'\" was skipped because it is not a recognized statement",
        line: 1,
      },
    ]);
  });

  it("records 之类的无大括号散行同样按行截断并带正确行号", () => {
    const r = parseDBML(
      "Table users { id int [pk] }\nrecords of migration\nTable orders { id int [pk] }",
    );
    expect(r.tables.map((t) => t.name)).toEqual(["users", "orders"]);
    expect(r.warnings?.map((w) => [w.code, w.line])).toEqual([["statement_skipped", 2]]);
  });

  it("文件尾部落单的散行也发警告", () => {
    const r = parseDBML("Table a { id int [pk] }\nNote: 'end'");
    expect(r.tables.map((t) => t.name)).toEqual(["a"]);
    expect(r.warnings?.map((w) => [w.code, w.line])).toEqual([["statement_skipped", 2]]);
  });

  it("多行 Ref 短句（运算符在下一行）不受截断影响", () => {
    const r = parseDBML(`
      Table a { id int [pk] }
      Table b { id int [pk]; aid int }
      Ref fk_b_a:
        b.aid > a.id
    `);
    expect(r.relationships.map((x) => [x.from, x.to, x.label])).toEqual([["b", "a", "aid"]]);
    expect(r.warnings).toBeUndefined();
  });

  it("大括号换行开写的 Table 块仍然有效", () => {
    const r = parseDBML("Table users\n{\n  id int [pk]\n}");
    expect(r.tables.map((t) => t.name)).toEqual(["users"]);
    expect(r.warnings).toBeUndefined();
  });
});

describe("parseDBML — `<` / `<>` 的 FK 归属", () => {
  it("`<` 时 FK 挂到右侧表，菱形标签取真实 FK 列", () => {
    const r = parseDBML(`
      Table users {
        id int [pk]
        email varchar
      }
      Table subs {
        id int [pk]
        user_id int
      }
      Ref: users.id < subs.user_id
    `);
    expect(r.relationships).toEqual([
      {
        from: "users",
        to: "subs",
        label: "user_id",
        fromCardinality: "1",
        toCardinality: "N",
      },
    ]);
    const users = r.tables.find((t) => t.name === "users")!;
    const subs = r.tables.find((t) => t.name === "subs")!;
    // FK 记录在真正持有 FK 的 subs 上；users 的属性椭圆不再被错误隐藏
    expect(users.foreignKeys).toEqual([]);
    expect(subs.foreignKeys).toEqual([
      { column: "user_id", referencedTable: "users", referencedColumn: "id" },
    ]);
  });

  it("`<>` 多对多不生成任何单侧 FK 记录", () => {
    const r = parseDBML(`
      Table users { id int [pk] }
      Table groups { id int [pk] }
      Ref: users.id <> groups.id
    `);
    expect(r.relationships[0].fromCardinality).toBe("N");
    expect(r.relationships[0].toCardinality).toBe("N");
    expect(r.tables.every((t) => t.foreignKeys.length === 0)).toBe(true);
  });
});

describe("parseDBML — 表别名", () => {
  it("Ref 中使用别名不再误报 missing table，且归一化为真实表名", () => {
    const r = parseDBML(`
      Table orders as O {
        id int [pk]
        user_id int [unique]
      }
      Table users { id int [pk] }
      Ref: O.user_id > users.id
    `);
    expect(r.warnings).toBeUndefined();
    expect(r.relationships).toEqual([
      // user_id 带 unique → 1:1 推断在别名归一化后依旧生效
      {
        from: "orders",
        to: "users",
        label: "user_id",
        fromCardinality: "1",
        toCardinality: "1",
      },
    ]);
    const orders = r.tables.find((t) => t.name === "orders")!;
    expect(orders.foreignKeys).toEqual([
      { column: "user_id", referencedTable: "users", referencedColumn: "id" },
    ]);
  });

  it("别名出现在 to 端同样归一化", () => {
    const r = parseDBML(`
      Table orders as O { id int [pk] }
      Table users { id int [pk]; order_id int }
      Ref: users.order_id > O.id
    `);
    expect(r.warnings).toBeUndefined();
    expect(r.relationships[0].to).toBe("orders");
  });

  it("Ref 出现在别名表定义之前也能命中（后置归一化）", () => {
    const r = parseDBML(`
      Ref: O.user_id > users.id
      Table orders as O { id int [pk]; user_id int }
      Table users { id int [pk] }
    `);
    expect(r.warnings).toBeUndefined();
    expect(r.relationships[0].from).toBe("orders");
    const orders = r.tables.find((t) => t.name === "orders")!;
    expect(orders.foreignKeys).toHaveLength(1);
  });
});

describe("parseDBML — from 端缺失表", () => {
  it("rel.from 指向未定义表时保留关系并告警", () => {
    const r = parseDBML(`
      Table users { id int [pk] }
      Ref: ghost.uid > users.id
    `);
    expect(r.relationships).toEqual([
      {
        from: "ghost",
        to: "users",
        label: "uid",
        fromCardinality: "N",
        toCardinality: "1",
      },
    ]);
    expect(r.warnings?.map((w) => w.message)).toEqual([
      'line 3: Ref references missing table "ghost"',
    ]);
  });
});

describe("parseDBML — Unicode 标识符", () => {
  it("韩文 / 日文假名表名与列名能解析", () => {
    const r = parseDBML(`
      Table 주문 {
        아이디 int [pk]
      }
      Table リスト {
        id int [pk]
        주문id int [ref: > 주문.아이디]
      }
    `);
    expect(r.tables.map((t) => t.name)).toEqual(["주문", "リスト"]);
    expect(r.tables[0].columns.map((c) => c.name)).toEqual(["아이디"]);
    expect(r.relationships.map((x) => [x.from, x.to, x.label])).toEqual([
      ["リスト", "주문", "주문id"],
    ]);
    expect(r.warnings).toBeUndefined();
  });

  it("原有中文标识符行为不回归", () => {
    const r = parseDBML(`
      Table 用户 { 编号 int [pk] }
    `);
    expect(r.tables[0].name).toBe("用户");
    expect(r.tables[0].primaryKeys).toEqual(["编号"]);
  });
});

describe("parseDBML — 重复表定义", () => {
  it("同名表重复定义时发 duplicate_table 警告", () => {
    const r = parseDBML("Table t { id int [pk] }\nTable t { name varchar }");
    expect(r.tables).toHaveLength(2);
    expect(r.warnings).toEqual([
      {
        code: "duplicate_table",
        message: 'line 2: table "t" is defined more than once',
        line: 2,
      },
    ]);
  });
});
